name: Testing
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  testing:
    name: Automated QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - profile: 'current-major'
          - profile: 'next-major'
    steps:
      - name: Custom action
        uses: psu-ooe/drupal-module-qa-action@main
        with:
          profile: ${{ matrix.profile }}
